apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-13T15:51:06Z"
  generation: 3
  labels:
    app: kubia
  name: kubia
  namespace: default
  resourceVersion: "150493"
  uid: 1a68c6c2-9a4c-4f67-aa95-fa0e087b2dee
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubia
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:1.0
        imagePullPolicy: IfNotPresent
        name: kubia
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-13T20:10:01Z"
  labels:
    app: kubia
  name: kubiaservice
  namespace: default
  resourceVersion: "78994"
  uid: b388fdfe-4eaf-4530-bf7a-21bf6dbc9533
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.152.183.193
  clusterIPs:
  - 10.152.183.193
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30856
    port: 1234
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia
  sessionAffinity: None
  type: LoadBalancer

